name: FastAPI CD

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "pypy3.10"

      - name: Create Venv
        run: python -m venv venv

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install numpy --no-binary numpy --build-options="--allow-noblas"
          pip install -r requirements.txt

      - name: Upload artifact to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          overwrite: true
          source: "venv,app,utils"
          target: "~/psy-omr"
