name: FastAPI CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Setup Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      # - name: Run Tests
      #   run: pipenv run pytest

      # - name: Lint Code
      #   run: |
      #     pipenv run flake8
